version: '3'

services:

  backend:
    container_name: secret_sharing_backend
    image: secret_sharing_backend:latest
    build:
      context: ./
      dockerfile: ./Backend/Dockerfile
    volumes:
       - ./Backend:/home/api
    expose:
      - 5000
    ports:
      - 5000:5000
    restart: always

  mongodb:
    image: mongo:latest # Get mongo image from docker
    ports:
      - "2017:27017" # Expose 2017 port in our system, But inside docker 27017 will be exposed
    volumes:
      - mongodb:/data/db # stores the mongo data in this location
  
volumes:
    mongodb: